bracketSameLine: false
importOrder:
  - '^[.][.]/app.scss'
  - '<THIRD_PARTY_MODULES>'
  - "^src/"
  - "^[./]"
importOrderSortSpecifiers: true
jsxSingleQuote: true
printWidth: 100
singleQuote: true
trailingComma: 'all'
