apiVersion: v1
kind: Template
metadata:
  name: automation-hub-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: automation-hub
    spec:
      envName: ${ENV_NAME}
      title: automation-hub
      deploymentRepo: https://github.com/ansible/ansible-hub-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/automation-hub
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - id: "collections"
          appId: "automationHub"
          title: "Collections"
          href: "/ansible/automation-hub/"
          icon: "AnsibleIcon"
          product: "Ansible Automation Hub"
          description: "Find and download Ansible Content Collections from Red Hat and partners."
        - id: "partners"
          appId: "automationHub"
          title: "Partners"
          href: "/ansible/automation-hub/partners"
          product: "Ansible Automation Hub"
        - id: "taskManagement"
          appId: "automationHub"
          title: "Task Management"
          href: "/ansible/automation-hub/tasks"
          product: "Ansible Automation Hub"
        - id: "connectToHub"
          appId: "automationHub"
          title: "Connect to Hub"
          href: "/ansible/automation-hub/token"
          product: "Ansible Automation Hub"
      module:
        manifestLocation: "/apps/automation-hub/fed-mods.json"
        modules:
          - id: "ansible-automation-hub"
            module: "./RootApp"
            routes:
              - pathname: /ansible/automation-hub

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/ansible-hub-ui
