export class SettingsType {
  GALAXY_AUTH_LDAP_ENABLED: never;
  GALAXY_AUTO_SIGN_COLLECTIONS: boolean;
  GALAXY_COLLECTION_SIGNING_SERVICE: string;
  GALAXY_CONTAINER_SIGNING_SERVICE: string;
  GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS: boolean;
  GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_DOWNLOAD: boolean;
  GALAXY_REQUIRE_CONTENT_APPROVAL: boolean;
  GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: boolean;
  GALAXY_FEATURE_FLAGS: never;
  GALAXY_SIGNATURE_UPLOAD_ENABLED: boolean;
  GALAXY_TOKEN_EXPIRATION: number | null;
  GALAXY_LDAP_DISABLE_REFERRALS: never;
  GALAXY_LDAP_MIRROR_ONLY_EXISTING_GROUPS: boolean;
  GALAXY_MINIMUM_PASSWORD_LENGTH: never;
  KEYCLOAK_URL: never;
}
