export class SettingsType {
  GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS: boolean;
  GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_DOWNLOAD: boolean;
  GALAXY_COLLECTION_SIGNING_SERVICE: string;
  GALAXY_REQUIRE_CONTENT_APPROVAL: boolean;
  GALAXY_AUTO_SIGN_COLLECTIONS: boolean;
  GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: boolean;
  GALAXY_SIGNATURE_UPLOAD_ENABLED: boolean;
  SIGNATURE_FINGERPRINT_LABELS: { [key: string]: string[] };
}
