name: Automerge

on:
  pull_request_target:
    branches: [ 'master', 'stable-*', 'feature/*' ]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout ansible-hub-ui (${{ github.ref }})"
      uses: actions/checkout@v4

    - name: "Install node 18"
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: "Run automerge.js"
      working-directory: ".github/workflows"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_TITLE: "${{ github.event.pull_request.title }}"
      run: |
        node automerge.js

    - name: "Automerge the PR"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Automerge of PR"
        gh pr merge "${{ github.event.pull_request.number }}" -s --auto
