name: Automerge

on:
  pull_request_target:
    branches: [ 'stable-*' ]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout ansible-hub-ui (${{ github.ref }})"
      uses: actions/checkout@v4

    - name: "Install node 20"
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: "Check automerge conditions"
      working-directory: ".github/workflows"
      env:
        PR_TITLE: "${{ github.event.pull_request.title }}"
      run: |
        node automerge-condition.js

    - name: "Wait for other tests"
      working-directory: ".github/workflows"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        node automerge-wait.js

    - name: "Automerge the PR"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr merge "${{ github.event.pull_request.number }}" -s --auto
