name: 'Add backported-* labels'

on:
  # allow running manually
  workflow_dispatch:
  push:
    branches: [ 'stable-*' ]
  pull_request: # debug
    branches: [ 'master' ] # debug

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
    - name: 'Set $LABEL from branch name'
      run: |
        GITHUB_REF='refs/heads/stable-4.2' # debug
        VERSION=`sed 's/^refs\/heads\/stable-//' <<< $GITHUB_REF`
        LABEL="backported-${VERSION}"
        echo "LABEL=${LABEL}" >> $GITHUB_ENV

    - uses: actions/checkout@v2
      with: # debug
        ref: 'stable-4.3' # debug

    - name: 'Set $PR to PR number'
      run: |
        git log -1 --oneline # debug
        echo PR=`git log -1 --oneline | perl -ne 'print if s/^.*?\(#(\d+)\).*\(#\d+\).*$/$1/'` >> $GITHUB_ENV

    - name: "Add ${{ env.LABEL }} to #${{ env.PR }}"
      if: ${{ env.PR }}
      run: |
        gh pr edit "$PR" --add-label "$LABEL"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
