name: "Push master to master-stable"

on:
  workflow_dispatch: # allow running manually
  schedule:
  - cron: '0 13 * * 2,4' # Tuesdays and Thursdays, 13:00 UTC

jobs:
  cloud:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout ansible-hub-ui-master, fail if paused, push to master-stable"
      run: |
        git clone -b master https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ansible/ansible-hub-ui.git
        cd ansible-hub-ui
        [ -f .cloud-stage-cron.enabled ] || exit 1
        git log -1 origin/master
        git log -1 origin/master-stable
        git push origin master:master-stable
