name: "Enable periodic stage deploy"

on:
  workflow_dispatch: # allow running manually

jobs:
  cloud:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout ansible-hub-ui master"
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: "Enable, push to master"
      run: |
        git config --global user.name 'GH Actions'
        git config --global user.email 'gh_actions@users.noreply.github.com'

        touch .cloud-stage-cron.enabled
        git add .cloud-stage-cron.enabled

        git commit -m 'Enable cloud stage cron deploy '`date --iso=d`
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ansible/ansible-hub-ui.git
        git push origin HEAD:master
