name: "Deploy cloud.redhat.com"

on:
  push:
    branches: [ "master", "prod-beta", "prod-stable" ]
  workflow_dispatch: # allow running manually
    inputs:
      beta:
        description: 'build for /beta/ urls'
        required: true
        type: boolean
      branch:
        description: 'target branch'
        required: true
        type: choice
        options:
        - prod-beta
        - prod-stable
        - qa-beta
        - qa-stable
      commit:
        description: 'deploy custom commit'
        required: true

concurrency:
  group: deploy-cloud-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cloud:
    runs-on: ubuntu-latest
    env:
      COMMIT_AUTHOR_EMAIL: ansible-hub-ui+cloud@example.com
      COMMIT_AUTHOR_USERNAME: rh-galaxy-droid
      CUSTOM_BETA: ${{ inputs.beta }}
      CUSTOM_BRANCH: ${{ inputs.branch }}
      NODE_OPTIONS: "--max-old-space-size=4096 --max_old_space_size=4096"
      REPO: "git@github.com:RedHatInsights/ansible-hub-ui-build.git"
      TRAVIS_EVENT_TYPE: "push"
      TRAVIS_PULL_REQUEST: "false"
      TRAVIS_TAG: ""
      encrypted__iv: ${{ secrets.encrypted__iv }}
      encrypted__key: ${{ secrets.encrypted__key }}

    steps:

    - name: "Checkout ansible-hub-ui (${{ github.ref }})"
      uses: actions/checkout@v2
      if: ${{ ! inputs.commit }}

    - name: "Checkout ansible-hub-ui (${{ inputs.commit }})"
      uses: actions/checkout@v3
      if: ${{ inputs.commit }}
      with:
        ref: ${{ inputs.commit }}

    - name: "Set BRANCH, TRAVIS_BRANCH, TRAVIS_BUILD_NUMBER, TRAVIS_WEB_URL, TRAVIS_COMMIT_MESSAGE"
      run: |
        TRAVIS_BRANCH=`sed 's/^refs\/heads\///' <<< $GITHUB_REF`
        [ -n "$CUSTOM_BRANCH" ] && TRAVIS_BRANCH="custom"
        TRAVIS_BUILD_NUMBER=$GITHUB_RUN_NUMBER
        TRAVIS_BUILD_WEB_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        TRAVIS_COMMIT_MESSAGE=`git log -1 --format=%B`
        echo "BRANCH=${CUSTOM_BRANCH:-$TRAVIS_BRANCH}" >> $GITHUB_ENV
        echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}" >> $GITHUB_ENV
        echo "TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}" >> $GITHUB_ENV
        echo "TRAVIS_BUILD_WEB_URL=${TRAVIS_BUILD_WEB_URL}" >> $GITHUB_ENV
        echo -e "TRAVIS_COMMIT_MESSAGE<<EOF\n${TRAVIS_COMMIT_MESSAGE}\nEOF" >> $GITHUB_ENV

    - name: "Install node 16"
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: "Cache ~/.npm"
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ env.GITHUB_REF }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ env.GITHUB_REF }}-
          ${{ runner.os }}-node-

    - name: "Build and deploy"
      run: |
        npm cache verify
        npm ci || npm install
        curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
