name: "Deploy cloud.redhat.com"

on:
  workflow_dispatch: # allow running manually
  push:
    branches: [ "master", "master-stable", "prod-beta", "prod-stable" ]

concurrency:
  group: deploy-cloud-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cloud:
    runs-on: ubuntu-latest
    env:
      COMMIT_AUTHOR_EMAIL: ansible-hub-ui+cloud@example.com
      COMMIT_AUTHOR_USERNAME: rh-galaxy-droid
      NODE_OPTIONS: "--max-old-space-size=4096 --max_old_space_size=4096"
      REPO: "git@github.com:RedHatInsights/ansible-hub-ui-build.git"
      TRAVIS_EVENT_TYPE: "push"
      TRAVIS_PULL_REQUEST: "false"
      TRAVIS_TAG: ""
      encrypted__iv: ${{ secrets.encrypted__iv }}
      encrypted__key: ${{ secrets.encrypted__key }}

    steps:

    - name: "Checkout ansible-hub-ui (${{ github.ref }})"
      uses: actions/checkout@v2

    - name: "Set BRANCH, TRAVIS_BRANCH, TRAVIS_BUILD_NUMBER, TRAVIS_WEB_URL, TRAVIS_COMMIT_MESSAGE"
      run: |
        TRAVIS_BRANCH=`sed 's/^refs\/heads\///' <<< $GITHUB_REF`
        TRAVIS_BUILD_NUMBER=$GITHUB_RUN_NUMBER
        TRAVIS_BUILD_WEB_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        TRAVIS_COMMIT_MESSAGE=`git log -1 --format=%B`
        echo "BRANCH=${TRAVIS_BRANCH}" >> $GITHUB_ENV
        echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}" >> $GITHUB_ENV
        echo "TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}" >> $GITHUB_ENV
        echo "TRAVIS_BUILD_WEB_URL=${TRAVIS_BUILD_WEB_URL}" >> $GITHUB_ENV
        echo -e "TRAVIS_COMMIT_MESSAGE<<EOF\n${TRAVIS_COMMIT_MESSAGE}\nEOF" >> $GITHUB_ENV

    - name: "Install node 14"
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: "Cache ~/.npm"
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ env.GITHUB_REF }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ env.GITHUB_REF }}-
          ${{ runner.os }}-node-

    - name: "Build and deploy"
      run: |
        npm cache verify
        npm ci || npm install
        npm run deploy && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
